// Derived from the original R2 drafts; no new recognition baseline.
// docs/evidence/wp17r2/results/win/diffs/ncnn-cpu-t4/zh_light_base.json SHA256 2adb32219e728048f92907b3bfa3a8c4a290269d66847710142c1bcde287de31
// docs/evidence/wp17r2/results/win/diffs/ncnn-cpu-t4/en_light_base.json SHA256 6cb92b20f1df9050896273c6a13ddf6b9a7515feb61f85fe883e016c657875aa
// docs/evidence/wp17r2/results/win/diffs/ncnn-cpu-t4/ja_light_base.json SHA256 1055d446ea7992b71f6a65c0e659b5587c9dcc8d4a18f9d46f633f03494014f2
const i6ReferenceDrafts = {
  "zh_light_base": [
    {
      "row": 3,
      "line_indices": [6, 5],
      "anchor_line": 6,
      "title": "买菜：西红柿、鸡蛋、牛奶",
      "checked": false,
      "checkbox_box": [48.0, 351.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": "今天18:00",
      "needs_confirmation": [],
    },
    {
      "row": 4,
      "line_indices": [7],
      "anchor_line": 7,
      "title": "给妈妈打电话",
      "checked": true,
      "checkbox_box": [48.0, 483.0, 45.0, 44.0],
      "checkbox_fill": 0.896,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 5,
      "line_indices": [8, 9],
      "anchor_line": 8,
      "title": "项目周报",
      "checked": false,
      "checkbox_box": [48.0, 615.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": "周五",
      "needs_confirmation": [],
    },
    {
      "row": 6,
      "line_indices": [10],
      "anchor_line": 10,
      "title": "整理上周会议记录",
      "checked": false,
      "checkbox_box": [104.0, 747.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 1,
      "parent": 5,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 7,
      "line_indices": [11],
      "anchor_line": 11,
      "title": "补充测试用例清单",
      "checked": false,
      "checkbox_box": [104.0, 879.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 1,
      "parent": 5,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 8,
      "line_indices": [12],
      "anchor_line": 12,
      "title": "读《DesigningData-Intensive》第5章",
      "checked": false,
      "checkbox_box": [48.0, 1011.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 9,
      "line_indices": [13, 14],
      "anchor_line": 13,
      "title": "缴纳水电费",
      "checked": false,
      "checkbox_box": [48.0, 1143.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": "10月15日",
      "needs_confirmation": [],
    },
    {
      "row": 10,
      "line_indices": [15],
      "anchor_line": 15,
      "title": "预约牙医9:30",
      "checked": true,
      "checkbox_box": [48.0, 1275.0, 45.0, 44.0],
      "checkbox_fill": 0.896,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
  ],
  "en_light_base": [
    {
      "row": 3,
      "line_indices": [5],
      "anchor_line": 5,
      "title": "Buygroceries:tomatoes,eggs,milkToday6:00PM",
      "checked": false,
      "checkbox_box": [48.0, 351.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 4,
      "line_indices": [7],
      "anchor_line": 7,
      "title": "Callmomback",
      "checked": true,
      "checkbox_box": [48.0, 483.0, 45.0, 44.0],
      "checkbox_fill": 0.896,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 5,
      "line_indices": [8, 9],
      "anchor_line": 8,
      "title": "Writeweeklystatusreport",
      "checked": false,
      "checkbox_box": [48.0, 615.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": "Fri",
      "needs_confirmation": [],
    },
    {
      "row": 6,
      "line_indices": [10],
      "anchor_line": 10,
      "title": "Tidyuplastweek'smeetingnotes",
      "checked": false,
      "checkbox_box": [104.0, 747.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 1,
      "parent": 5,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 7,
      "line_indices": [11],
      "anchor_line": 11,
      "title": "Fillintheregressiontestchecklist",
      "checked": false,
      "checkbox_box": [104.0, 879.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 1,
      "parent": 5,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 8,
      "line_indices": [12],
      "anchor_line": 12,
      "title": "Readchapter5ofDDIA",
      "checked": false,
      "checkbox_box": [48.0, 1011.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 9,
      "line_indices": [13, 14],
      "anchor_line": 13,
      "title": "Paytheutilitybill",
      "checked": false,
      "checkbox_box": [48.0, 1143.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": "Oct15",
      "needs_confirmation": [],
    },
    {
      "row": 10,
      "line_indices": [15],
      "anchor_line": 15,
      "title": "Dentistappointmentat9:30",
      "checked": true,
      "checkbox_box": [48.0, 1275.0, 45.0, 44.0],
      "checkbox_fill": 0.896,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
  ],
  "ja_light_base": [
    {
      "row": 3,
      "line_indices": [5],
      "anchor_line": 5,
      "title": "スーパーで食材を買う（トマト・卵今件乳",
      "checked": false,
      "checkbox_box": [48.0, 351.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 4,
      "line_indices": [6],
      "anchor_line": 6,
      "title": "母に電話をかける",
      "checked": true,
      "checkbox_box": [48.0, 483.0, 45.0, 44.0],
      "checkbox_fill": 0.896,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 5,
      "line_indices": [8, 9],
      "anchor_line": 8,
      "title": "週報を書く",
      "checked": false,
      "checkbox_box": [48.0, 615.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": "金曜",
      "needs_confirmation": [],
    },
    {
      "row": 6,
      "line_indices": [10],
      "anchor_line": 10,
      "title": "先週の議事録を整理する",
      "checked": false,
      "checkbox_box": [104.0, 747.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 1,
      "parent": 5,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 7,
      "line_indices": [11],
      "anchor_line": 11,
      "title": "回帰テストの項目を追加",
      "checked": false,
      "checkbox_box": [104.0, 879.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 1,
      "parent": 5,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 8,
      "line_indices": [12],
      "anchor_line": 12,
      "title": "技術書の第5章を読む",
      "checked": false,
      "checkbox_box": [48.0, 1011.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
    {
      "row": 9,
      "line_indices": [13, 14],
      "anchor_line": 13,
      "title": "公共料金を支払う",
      "checked": false,
      "checkbox_box": [48.0, 1143.0, 45.0, 44.0],
      "checkbox_fill": 0.248,
      "level": 0,
      "parent": null,
      "due": "10月15日",
      "needs_confirmation": [],
    },
    {
      "row": 10,
      "line_indices": [15],
      "anchor_line": 15,
      "title": "歯医者の予約9:30",
      "checked": true,
      "checkbox_box": [48.0, 1275.0, 45.0, 44.0],
      "checkbox_fill": 0.896,
      "level": 0,
      "parent": null,
      "due": null,
      "needs_confirmation": [],
    },
  ],
};
